//student class w last name
class Student {
    String  firstName;
    String  lastName;
    Integer age;

    public Student(String firstName, String lastName){
        this.firstName = firstName;
        this.lastName  = lastName;
    }
}

//create student
Student studentJohnny = New Student('John', 'Fuller Jr.');
System.debug('Results of student: '+ studentJohnny);
//generate new student
student jene = new Student('Jene', 'Fuller');
System.debug('New Student Jene: ' + jene);




